import type { Language } from "./src/i18n"

type GameItem = {
  titleZh: string
  titleEn: string
  score: number
}

// 数据来源：用户提供的 GameList.txt（2006–2025 各年综合关注度榜单，2006–2021 每年 10 款，2022 起 11–12 款；界面取前 12 款，全部展示）
// score 界面未使用，暂记 0，可后续填入真实评分
const data: Record<string, GameItem[]> = {
  "2006": [
    { titleZh: "魔兽世界", titleEn: "World of Warcraft", score: 0 },
    { titleZh: "梦幻西游", titleEn: "Fantasy Westward Journey", score: 0 },
    { titleZh: "征途", titleEn: "ZT Online", score: 0 },
    { titleZh: "热血传奇", titleEn: "The Legend of Mir 2", score: 0 },
    { titleZh: "劲舞团", titleEn: "Audition", score: 0 },
    { titleZh: "完美世界", titleEn: "Perfect World", score: 0 },
    { titleZh: "跑跑卡丁车", titleEn: "KartRider", score: 0 },
    { titleZh: "新超级马力欧兄弟", titleEn: "New Super Mario Bros.", score: 0 },
    { titleZh: "上古卷轴 IV：湮没", titleEn: "The Elder Scrolls IV: Oblivion", score: 0 },
    { titleZh: "冒险岛", titleEn: "MapleStory", score: 0 },
  ],
  "2007": [
    { titleZh: "光环3", titleEn: "Halo 3", score: 0 },
    { titleZh: "使命召唤4：现代战争", titleEn: "Call of Duty 4: Modern Warfare", score: 0 },
    { titleZh: "超级马力欧银河", titleEn: "Super Mario Galaxy", score: 0 },
    { titleZh: "天龙八部", titleEn: "Dragon Oath", score: 0 },
    { titleZh: "诛仙", titleEn: "Jade Dynasty", score: 0 },
    { titleZh: "生化奇兵", titleEn: "BioShock", score: 0 },
    { titleZh: "孤岛危机", titleEn: "Crysis", score: 0 },
    { titleZh: "宝可梦 钻石/珍珠", titleEn: "Pokémon Diamond and Pearl", score: 0 },
    { titleZh: "吉他英雄3：摇滚传奇", titleEn: "Guitar Hero III: Legends of Rock", score: 0 },
    { titleZh: "神秘海域：德雷克的宝藏", titleEn: "Uncharted: Drake's Fortune", score: 0 },
  ],
  "2008": [
    { titleZh: "侠盗猎车手IV", titleEn: "Grand Theft Auto IV", score: 0 },
    { titleZh: "地下城与勇士", titleEn: "Dungeon Fighter Online", score: 0 },
    { titleZh: "穿越火线", titleEn: "CrossFire", score: 0 },
    { titleZh: "Wii Fit", titleEn: "Wii Fit", score: 0 },
    { titleZh: "辐射3", titleEn: "Fallout 3", score: 0 },
    { titleZh: "求生之路", titleEn: "Left 4 Dead", score: 0 },
    { titleZh: "QQ飞车", titleEn: "QQ Speed", score: 0 },
    { titleZh: "孢子", titleEn: "Spore", score: 0 },
    { titleZh: "摇滚乐队", titleEn: "Rock Band", score: 0 },
  ],
  "2009": [
    { titleZh: "使命召唤：现代战争2", titleEn: "Call of Duty: Modern Warfare 2", score: 0 },
    { titleZh: "刺客信条II", titleEn: "Assassin's Creed II", score: 0 },
    { titleZh: "Wii运动 度假胜地", titleEn: "Wii Sports Resort", score: 0 },
    { titleZh: "新超级马力欧兄弟 Wii", titleEn: "New Super Mario Bros. Wii", score: 0 },
    { titleZh: "生化危机5", titleEn: "Resident Evil 5", score: 0 },
    { titleZh: "植物大战僵尸", titleEn: "Plants vs. Zombies", score: 0 },
    { titleZh: "求生之路2", titleEn: "Left 4 Dead 2", score: 0 },
    { titleZh: "龙之谷", titleEn: "Dragon Nest", score: 0 },
    { titleZh: "剑网3", titleEn: "JX Online 3", score: 0 },
    { titleZh: "龙腾世纪：起源", titleEn: "Dragon Age: Origins", score: 0 },
  ],
  "2010": [
    { titleZh: "使命召唤：黑色行动", titleEn: "Call of Duty: Black Ops", score: 0 },
    { titleZh: "荒野大镖客：救赎", titleEn: "Red Dead Redemption", score: 0 },
    { titleZh: "星际争霸II：自由之翼", titleEn: "StarCraft II: Wings of Liberty", score: 0 },
    { titleZh: "FIFA 11", titleEn: "FIFA 11", score: 0 },
    { titleZh: "光环：致远星", titleEn: "Halo: Reach", score: 0 },
    { titleZh: "愤怒的小鸟", titleEn: "Angry Birds", score: 0 },
    { titleZh: "QQ农场", titleEn: "QQ Farm", score: 0 },
    { titleZh: "FarmVille", titleEn: "FarmVille", score: 0 },
    { titleZh: "神武", titleEn: "Shenwu", score: 0 },
    { titleZh: "NBA 2K11", titleEn: "NBA 2K11", score: 0 },
  ],
  "2011": [
    { titleZh: "我的世界", titleEn: "Minecraft", score: 0 },
    { titleZh: "上古卷轴V：天际", titleEn: "The Elder Scrolls V: Skyrim", score: 0 },
    { titleZh: "英雄联盟", titleEn: "League of Legends", score: 0 },
    { titleZh: "使命召唤：现代战争3", titleEn: "Call of Duty: Modern Warfare 3", score: 0 },
    { titleZh: "战地3", titleEn: "Battlefield 3", score: 0 },
    { titleZh: "坦克世界", titleEn: "World of Tanks", score: 0 },
    { titleZh: "黑暗之魂", titleEn: "Dark Souls", score: 0 },
    { titleZh: "传送门2", titleEn: "Portal 2", score: 0 },
    { titleZh: "泰拉瑞亚", titleEn: "Terraria", score: 0 },
    { titleZh: "神秘海域3：德雷克的诡计", titleEn: "Uncharted 3: Drake's Deception", score: 0 },
  ],
  "2012": [
    { titleZh: "暗黑破坏神III", titleEn: "Diablo III", score: 0 },
    { titleZh: "使命召唤：黑色行动II", titleEn: "Call of Duty: Black Ops II", score: 0 },
    { titleZh: "孤岛惊魂3", titleEn: "Far Cry 3", score: 0 },
    { titleZh: "无主之地2", titleEn: "Borderlands 2", score: 0 },
    { titleZh: "刺客信条III", titleEn: "Assassin's Creed III", score: 0 },
    { titleZh: "FIFA 13", titleEn: "FIFA 13", score: 0 },
    { titleZh: "激战2", titleEn: "Guild Wars 2", score: 0 },
    { titleZh: "羞辱", titleEn: "Dishonored", score: 0 },
    { titleZh: "行尸走肉", titleEn: "The Walking Dead", score: 0 },
    { titleZh: "部落冲突", titleEn: "Clash of Clans", score: 0 },
  ],
  "2013": [
    { titleZh: "侠盗猎车手V", titleEn: "Grand Theft Auto V", score: 0 },
    { titleZh: "最后生还者", titleEn: "The Last of Us", score: 0 },
    { titleZh: "Dota 2", titleEn: "Dota 2", score: 0 },
    { titleZh: "宝可梦 X / Y", titleEn: "Pokémon X and Y", score: 0 },
    { titleZh: "剑灵", titleEn: "Blade & Soul", score: 0 },
    { titleZh: "FIFA 14", titleEn: "FIFA 14", score: 0 },
    { titleZh: "刺客信条IV：黑旗", titleEn: "Assassin's Creed IV: Black Flag", score: 0 },
    { titleZh: "神庙逃亡2", titleEn: "Temple Run 2", score: 0 },
    { titleZh: "糖果传奇", titleEn: "Candy Crush Saga", score: 0 },
    { titleZh: "战地4", titleEn: "Battlefield 4", score: 0 },
  ],
  "2014": [
    { titleZh: "Flappy Bird", titleEn: "Flappy Bird", score: 0 },
    { titleZh: "命运1（命运系列）", titleEn: "Destiny", score: 0 },
    { titleZh: "炉石传说", titleEn: "Hearthstone", score: 0 },
    { titleZh: "看门狗", titleEn: "Watch Dogs", score: 0 },
    { titleZh: "玩具熊的五夜后宫", titleEn: "Five Nights at Freddy's", score: 0 },
    { titleZh: "模拟人生4", titleEn: "The Sims 4", score: 0 },
    { titleZh: "FIFA 15", titleEn: "FIFA 15", score: 0 },
    { titleZh: "使命召唤：高级战争", titleEn: "Call of Duty: Advanced Warfare", score: 0 },
    { titleZh: "开心消消乐", titleEn: "Anipop", score: 0 },
  ],
  "2015": [
    { titleZh: "巫师3：狂猎", titleEn: "The Witcher 3: Wild Hunt", score: 0 },
    { titleZh: "辐射4", titleEn: "Fallout 4", score: 0 },
    { titleZh: "使命召唤：黑色行动III", titleEn: "Call of Duty: Black Ops III", score: 0 },
    { titleZh: "梦幻西游手游", titleEn: "Fantasy Westward Journey", score: 0 },
    { titleZh: "火箭联盟", titleEn: "Rocket League", score: 0 },
    { titleZh: "血源诅咒", titleEn: "Bloodborne", score: 0 },
    { titleZh: "合金装备V：幻痛", titleEn: "Metal Gear Solid V: The Phantom Pain", score: 0 },
    { titleZh: "斯普拉遁", titleEn: "Splatoon", score: 0 },
    { titleZh: "Undertale", titleEn: "Undertale", score: 0 },
    { titleZh: "蝙蝠侠：阿卡姆骑士", titleEn: "Batman: Arkham Knight", score: 0 },
  ],
  "2016": [
    { titleZh: "Pokémon GO", titleEn: "Pokémon GO", score: 0 },
    { titleZh: "王者荣耀", titleEn: "Honor of Kings", score: 0 },
    { titleZh: "守望先锋", titleEn: "Overwatch", score: 0 },
    { titleZh: "阴阳师", titleEn: "Onmyoji", score: 0 },
    { titleZh: "战地1", titleEn: "Battlefield 1", score: 0 },
    { titleZh: "最终幻想XV", titleEn: "Final Fantasy XV", score: 0 },
    { titleZh: "神秘海域4：盗贼末路", titleEn: "Uncharted 4: A Thief's End", score: 0 },
    { titleZh: "黑暗之魂III", titleEn: "Dark Souls III", score: 0 },
    { titleZh: "星露谷物语", titleEn: "Stardew Valley", score: 0 },
    { titleZh: "毁灭战士", titleEn: "DOOM", score: 0 },
  ],
  "2017": [
    { titleZh: "绝地求生", titleEn: "PUBG: Battlegrounds", score: 0 },
    { titleZh: "塞尔达传说：旷野之息", titleEn: "The Legend of Zelda: Breath of the Wild", score: 0 },
    { titleZh: "超级马力欧：奥德赛", titleEn: "Super Mario Odyssey", score: 0 },
    { titleZh: "生化危机7：生化危机", titleEn: "Resident Evil 7: Biohazard", score: 0 },
    { titleZh: "尼尔：机械纪元", titleEn: "NieR:Automata", score: 0 },
    { titleZh: "地平线：零之曙光", titleEn: "Horizon Zero Dawn", score: 0 },
    { titleZh: "使命召唤：二战", titleEn: "Call of Duty: WWII", score: 0 },
    { titleZh: "FIFA 18", titleEn: "FIFA 18", score: 0 },
    { titleZh: "刺客信条：起源", titleEn: "Assassin's Creed Origins", score: 0 },
    { titleZh: "荒野行动（吃鸡手游大类）", titleEn: "Knives Out", score: 0 },
  ],
  "2018": [
    { titleZh: "堡垒之夜", titleEn: "Fortnite", score: 0 },
    { titleZh: "荒野大镖客：救赎2", titleEn: "Red Dead Redemption 2", score: 0 },
    { titleZh: "第五人格", titleEn: "Identity V", score: 0 },
    { titleZh: "战神", titleEn: "God of War", score: 0 },
    { titleZh: "怪物猎人：世界", titleEn: "Monster Hunter: World", score: 0 },
    { titleZh: "漫威蜘蛛侠", titleEn: "Marvel's Spider-Man", score: 0 },
    { titleZh: "任天堂明星大乱斗 特别版", titleEn: "Super Smash Bros. Ultimate", score: 0 },
    { titleZh: "明日之后", titleEn: "LifeAfter", score: 0 },
    { titleZh: "宝可梦 Let's Go！皮卡丘/伊布", titleEn: "Pokémon: Let's Go, Pikachu! / Let's Go, Eevee!", score: 0 },
    { titleZh: "辐射76", titleEn: "Fallout 76", score: 0 },
  ],
  "2019": [
    { titleZh: "Apex 英雄", titleEn: "Apex Legends", score: 0 },
    { titleZh: "使命召唤：现代战争", titleEn: "Call of Duty: Modern Warfare", score: 0 },
    { titleZh: "明日方舟", titleEn: "Arknights", score: 0 },
    { titleZh: "宝可梦 剑/盾", titleEn: "Pokémon Sword and Shield", score: 0 },
    { titleZh: "只狼：影逝二度", titleEn: "Sekiro: Shadows Die Twice", score: 0 },
    { titleZh: "生化危机2", titleEn: "Resident Evil 2", score: 0 },
    { titleZh: "使命召唤手游", titleEn: "Call of Duty: Mobile", score: 0 },
    { titleZh: "云顶之弈", titleEn: "Teamfight Tactics", score: 0 },
    { titleZh: "三国志·战略版", titleEn: "Three Kingdoms: Strategy Edition", score: 0 },
    { titleZh: "无主之地3", titleEn: "Borderlands 3", score: 0 },
  ],
  "2020": [
    { titleZh: "集合啦！动物森友会", titleEn: "Animal Crossing: New Horizons", score: 0 },
    { titleZh: "原神", titleEn: "Genshin Impact", score: 0 },
    { titleZh: "使命召唤：战区", titleEn: "Call of Duty: Warzone", score: 0 },
    { titleZh: "Among Us / 太空狼人杀", titleEn: "Among Us", score: 0 },
    { titleZh: "糖豆人：终极淘汰赛", titleEn: "Fall Guys: Ultimate Knockout", score: 0 },
    { titleZh: "无畏契约", titleEn: "VALORANT", score: 0 },
    { titleZh: "赛博朋克2077", titleEn: "Cyberpunk 2077", score: 0 },
    { titleZh: "光·遇", titleEn: "Sky: Children of the Light", score: 0 },
    { titleZh: "最后生还者 Part II", titleEn: "The Last of Us Part II", score: 0 },
    { titleZh: "对马岛之魂", titleEn: "Ghost of Tsushima", score: 0 },
  ],
  "2021": [
    { titleZh: "Roblox", titleEn: "Roblox", score: 0 },
    { titleZh: "永劫无间", titleEn: "NARAKA: BLADEPOINT", score: 0 },
    { titleZh: "双人成行", titleEn: "It Takes Two", score: 0 },
    { titleZh: "生化危机：村庄", titleEn: "Resident Evil Village", score: 0 },
    { titleZh: "极限竞速：地平线5", titleEn: "Forza Horizon 5", score: 0 },
    { titleZh: "战地2042", titleEn: "Battlefield 2042", score: 0 },
    { titleZh: "光环：无限", titleEn: "Halo Infinite", score: 0 },
    { titleZh: "新世界", titleEn: "New World", score: 0 },
    { titleZh: "Valheim：英灵神殿", titleEn: "Valheim", score: 0 },
    { titleZh: "哈利波特：魔法觉醒", titleEn: "Harry Potter: Magic Awakened", score: 0 },
    { titleZh: "金铲铲之战", titleEn: "Golden Spatula", score: 0 },
  ],
  "2022": [
    { titleZh: "艾尔登法环", titleEn: "Elden Ring", score: 0 },
    { titleZh: "使命召唤：现代战争II", titleEn: "Call of Duty: Modern Warfare II", score: 0 },
    { titleZh: "宝可梦 朱/紫", titleEn: "Pokémon Scarlet and Violet", score: 0 },
    { titleZh: "羊了个羊", titleEn: "Sheep a Sheep", score: 0 },
    { titleZh: "宝可梦传说：阿尔宙斯", titleEn: "Pokémon Legends: Arceus", score: 0 },
    { titleZh: "战神：诸神黄昏", titleEn: "God of War Ragnarök", score: 0 },
    { titleZh: "失落的方舟", titleEn: "Lost Ark", score: 0 },
    { titleZh: "Stray / 流浪猫", titleEn: "Stray", score: 0 },
    { titleZh: "幻塔", titleEn: "Tower of Fantasy", score: 0 },
    { titleZh: "吸血鬼幸存者", titleEn: "Vampire Survivors", score: 0 },
  ],
  "2023": [
    { titleZh: "霍格沃茨之遗", titleEn: "Hogwarts Legacy", score: 0 },
    { titleZh: "博德之门3", titleEn: "Baldur's Gate 3", score: 0 },
    { titleZh: "塞尔达传说：王国之泪", titleEn: "The Legend of Zelda: Tears of the Kingdom", score: 0 },
    { titleZh: "崩坏：星穹铁道", titleEn: "Honkai: Star Rail", score: 0 },
    { titleZh: "蛋仔派对", titleEn: "Eggy Party", score: 0 },
    { titleZh: "生化危机4", titleEn: "Resident Evil 4", score: 0 },
    { titleZh: "星空", titleEn: "Starfield", score: 0 },
    { titleZh: "反恐精英2", titleEn: "Counter-Strike 2", score: 0 },
    { titleZh: "逆水寒手游", titleEn: "Justice Mobile", score: 0 },
    { titleZh: "暗黑破坏神IV", titleEn: "Diablo IV", score: 0 },
    { titleZh: "边狱巴士", titleEn: "Limbus Company", score: 0 },
    { titleZh: "潜水员戴夫", titleEn: "Dave the Diver", score: 0 },
  ],
  "2024": [
    { titleZh: "黑神话：悟空", titleEn: "Black Myth: Wukong", score: 0 },
    { titleZh: "鸣潮", titleEn: "Wuthering Waves", score: 0 },
    { titleZh: "绝区零", titleEn: "Zenless Zone Zero", score: 0 },
	{ titleZh: "三角洲行动", titleEn: "Delta Force", score: 0 },
    { titleZh: "幻兽帕鲁", titleEn: "Palworld", score: 0 },
    { titleZh: "地狱潜者2", titleEn: "Helldivers 2", score: 0 },
    { titleZh: "EA Sports FC 25", titleEn: "EA Sports FC 25", score: 0 },
    { titleZh: "使命召唤：黑色行动6", titleEn: "Call of Duty: Black Ops 6", score: 0 },
    { titleZh: "最终幻想VII：重生", titleEn: "Final Fantasy VII Rebirth", score: 0 },
    { titleZh: "漫威争锋", titleEn: "Marvel Rivals", score: 0 },
    { titleZh: "寂静岭2", titleEn: "Silent Hill 2", score: 0 },
    { titleZh: "Balatro", titleEn: "Balatro", score: 0 },
  ],
  "2025": [
    { titleZh: "怪物猎人：荒野", titleEn: "Monster Hunter Wilds", score: 0 },
    { titleZh: "燕云十六声", titleEn: "Where Winds Meet", score: 0 },
    { titleZh: "光与影：33号远征队", titleEn: "Clair Obscur: Expedition 33", score: 0 },
    { titleZh: "王国风云：救赎2 / 天国：拯救2", titleEn: "Kingdom Come: Deliverance II", score: 0 },
    { titleZh: "双影奇境", titleEn: "Split Fiction", score: 0 },
    { titleZh: "刺客信条：影", titleEn: "Assassin's Creed Shadows", score: 0 },
    { titleZh: "宝可梦传说：Z-A", titleEn: "Pokémon Legends: Z-A", score: 0 },
    { titleZh: "R.E.P.O.", titleEn: "R.E.P.O.", score: 0 },
    { titleZh: "PEAK", titleEn: "PEAK", score: 0 },
    { titleZh: "Schedule I", titleEn: "Schedule I", score: 0 },
  ],
}

// 添加一个辅助函数来根据语言获取游戏标题
export const getGameTitle = (game: GameItem, language: Language): string => {
  return game[
    ("title" +
      language.charAt(0).toUpperCase() +
      language.slice(1)) as keyof GameItem
  ] as string
}

export default data
